<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <RootNamespace>EcoEnergyManagement.PlatformHelpers</RootNamespace>
        <UseWinUI>true</UseWinUI>
        <WinUISDKReferences>false</WinUISDKReferences>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <Platforms>AnyCPU;x64</Platforms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
        <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.333">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2705" />
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="NativeMethods\" />
        <AdditionalFiles Include="NativeMethods\NativeMethods.txt" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\EcoEnergyManagement.Core\EcoEnergyManagement.Core.csproj" />
    </ItemGroup>
</Project>